In [1]:
from PIL import Image
import numpy as np
from numpy import array
import matplotlib.image as img
from  scipy import misc
import cv2

In [2]:
def main():
    im = cv2.imread("puppy.jpg")
    dim = im.shape
    dim = list(dim)
    dim.sort()
    image = np.resize
    image = np.reshape(im, (dim[0],dim[1],dim[2]))
    
    
    filter = [   [[1,0,1],
             [0,1,0],
             [1,0,1]] ,
        
             [[-1,0,1],
             [0,1,0],
             [1,0,-1]] ]
    '''
             [[1,0,-1],
             [0,-1,0],
             [1,0,1]],
             
             [[1,0,-1],
             [0,-1,0],
             [-1,0,1]],
          
             [[-1,0,-1],
             [0,1,0],
             [1,0,1]],
          
             [[1,0,1],
             [0,-1,0],
             [1,0,1]],
          
             [[1,0,1],
             [0,1,0],
             [-1,0,-1]],
          
             [[-2,0,-1],
             [0,-1,0],
             [1,0,2]],
          
             [[1,0,-2],
             [0,1,0],
             [2,0,-1]],
          
             [[1,1,0],
             [-1,-1,1],
             [-1,0,1]]
         ]
    '''
    filter = np.array(filter)
    stride = 1
    m = len(filter)
    myconv2D(image,m,filter,stride)


In [3]:
def myconv2D(image, m, filters, s):
    print("\nInput Array is \n",image)
    
    shape = image.shape
    
    l = shape[2]#len(image[0])
    b = shape[1]#len(image[0][0])
    d = shape[0]#len(image)
    
    f_l = len(filters[0])
    f_b = len(filters[0][0])
    f_d = d
    
    o_l = (l-f_l+1)//s
    o_b = (b-f_b+1)//s        
    o_d = (d-f_d+1)//s
    
    # when input image is 2D
    if o_d == 0:
        o_d = 1
        
    print("\nInput dimensions are - ",l,b,d)
    print("Output dimensions are - ",o_l,o_b,o_d)
    print()
    
    if m <= 0:
        print("Number of filters cant be negative")
        return False
    if s > l or s > b:
        print("Stride Exceeded : convolution cant be performed")
        return False    
   
    
    output = np.zeros([o_b,o_l], dtype = int)
    
    # logic to calculate convoluted matrix for each filter
    for x in range(len(filters)): # for each filter
        for k in range(0,d):  # for each depth
            for i in range(0,o_b): # for each row
                for j in range(0,o_l): # for each column
                    sum=0
                    
                    # calculate value of each cell 
                    for m in range(0,f_l):
                        for n in range(0,f_b):
                            sum = sum + filters[x][m][n]*image[k][m+i][n+j]
                    
                    # output of each channel
                    output[i][j] += sum
        print("\nOutput with filter ",x+1," is")
        print(output)
        output = np.zeros([o_b,o_l], dtype = int)

In [4]:
main()


Input Array is 
 [[[232 227 226 ... 235 234 240]
  [235 234 240 ... 234 240 235]
  [234 240 235 ... 147 153 152]
  ...
  [ 58 105 132 ... 155 186 102]
  [159 190 109 ... 139  67 118]
  [138  67 118 ...  20  69  77]]

 [[ 58 105 132 ... 156 187 102]
  [157 188 109 ... 142  70 120]
  [142  69 119 ...  23  72  82]
  ...
  [ 80 138 157 ... 162 183 106]
  [161 182 102 ... 175 102 162]
  [174 102 162 ...  83 141 153]]

 [[ 82 138 157 ... 161 184 107]
  [162 183 103 ... 176 105 162]
  [177 105 162 ...  84 143 153]
  ...
  [ 23 100  96 ... 151 163  90]
  [151 161  96 ... 167 104 159]
  [174 105 160 ...  46  94 100]]]

Input dimensions are -  388 258 3
Output dimensions are -  386 256 1


Output with filter  1  is
[[2561 2260 2471 ... 2301 2364 2057]
 [2305 2522 2596 ... 2515 2247 2441]
 [2544 2645 2359 ... 2053 2252 2324]
 ...
 [1585 1948 2047 ... 2071 1676 1980]
 [2042 2152 1713 ... 1491 1802 1921]
 [2005 1572 1921 ... 1889 1944 1518]]

Output with filter  2  is
[[ 785  216  621 ...  581  72